apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qsan-csi-pvc-ex
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 6Gi
  storageClassName: qsan-xevo-storage-ex