apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qsan-csi-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: qsan-xevo-storage
