apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qsan-csi-pvc2
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: qsan-xevo-storage
